project_name: squarecloud

release:
  name_template: "Square Cloud CLI {{ .Version }}"

builds:
  - main: ./cmd/squarecloud
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X squarecloud/internal/build.Version={{ .Version }}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - builds:
      - squarecloud
    vendor: richaardev
    maintainer: "richaardev <me@richaar.dev>"
    license: MIT
    formats:
      - deb
      - rpm
      - termux.deb
    bindir: /usr/bin

brews:
  - homepage: "https://github.com/richaardev/"
    description: "Square Cloud CLI Aplication"
    folder: Formula
    license: MIT
    tap:
      owner: richaardev
      name: homebrew-squarecloud